# Generated by Django 2.1.2 on 2018-10-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0004_auto_20181030_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='build',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='damageBonus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
