# Generated by Django 2.1.2 on 2018-10-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0007_character_bottom_lips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='bottom_lips',
            new_name='bottom_lip',
        ),
        migrations.AddField(
            model_name='character',
            name='eyes_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='face',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.FaceShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='face_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_eye',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.LeftEyeLidShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='lips_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='right_eye',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.RightEyeLidShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='upper_lip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.UpperLipShape'),
        ),
        migrations.AddField(
            model_name='hair',
            name='height',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hair',
            name='left',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hair',
            name='top',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hair',
            name='width',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
