# Generated by Django 2.1.2 on 2018-11-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0012_auto_20181113_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bottom_lip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.BottomLipShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='face',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.FaceShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='face_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='left_eye',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.LeftEyeLidShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='lips_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='right_eye',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.RightEyeLidShape'),
        ),
        migrations.AddField(
            model_name='character',
            name='upper_lip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cthulhu.UpperLipShape'),
        ),
    ]
