# Generated by Django 2.1.2 on 2018-11-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0013_auto_20181113_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='bottom_lip',
        ),
        migrations.RemoveField(
            model_name='character',
            name='eyes_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='face',
        ),
        migrations.RemoveField(
            model_name='character',
            name='face_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='character',
            name='left_eye',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lips_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='right_eye',
        ),
        migrations.RemoveField(
            model_name='character',
            name='upper_lip',
        ),
    ]
