# Generated by Django 2.1.2 on 2018-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0014_auto_20181114_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.ImageField(blank=True, upload_to='characters'),
        ),
    ]
