# Generated by Django 2.1.2 on 2018-11-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0017_auto_20181122_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='creditRating',
            new_name='cash',
        ),
    ]
