# Generated by Django 2.1.2 on 2018-11-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0017_character_owner'),
        ('cthulhu', '0018_auto_20181122_1158'),
    ]

    operations = [
    ]
