# Generated by Django 2.1.2 on 2018-11-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0019_merge_20181126_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterskill',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.DeleteModel(
            name='CharacterSkill',
        ),
    ]
