# Generated by Django 2.1.2 on 2018-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0020_auto_20181128_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appear',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.ImageField(upload_to='characters'),
        ),
        migrations.AlterField(
            model_name='character',
            name='birthCity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='build',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='cash',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='damageBonus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='education',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='gamer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPoints',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='interests',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='luck',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='magicPoints',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='power',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='sanity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.CharField(default='', max_length=100),
        ),
    ]
